### ISSUE TITLE
No query in the released version 0.3.1

### ISSUE THREAD

**Issue by kiwiupover** [mydea/ember-keen#1]
I was excited to query keen. Is another release in order?

**Comment by mydea** [comment]
I have implemented it, but haven't had the time to test it in an actual project so far. 
I would appreciate it if you would install the latest version from the master branch and try it out. So in your package.json you'll need to have `"ember-keen": "ember-keen/master"`.

If you have any problems, I'll try to fix them. If not, I'll release it as 0.4.0 :)

**Comment by mydea** [comment]
This has been released as 0.4.0!
