### ISSUE TITLE
Nested API parameters doesn't work in query() method

### ISSUE THREAD

**Issue by arm1n** [mydea/ember-keen#2]
Using `query()` with nested data parameters doesn't work with current implementation for an invokation like:

```
keen.query('count', 'listing-view', {
	timeframe: {
		start: '2010-01-01T12:00:00Z',
		end: '2010-01-10T12:00:00Z'
	}
)
```

It seems like Keen API doesn't extract query string parameters correctly. Changing the request methodology to using `POST` and sending it via request body works as expected.

**Comment by mydea** [comment]
Closed via #3
